## Task 1 ##

In [1]:
import numpy as np
import math

In [2]:
M = np.matrix([
    [2,1,1,10],
    [3,2,3,18],
    [1,4,9,16],
])

In [3]:
eq1 = M[2,:]*2 - M[0,:]
eq1

matrix([[ 0,  7, 17, 22]])

In [4]:
eq2 = (M[2,:]*3-M[1,:])/2
eq2

matrix([[ 0.,  5., 12., 15.]])

In [5]:
eq3 = eq2*(7/5)
eq3

matrix([[ 0. ,  7. , 16.8, 21. ]])

In [70]:
eq4 = (eq1-eq3)*5
eq4=eq4.astype(int)
eq4

matrix([[0, 0, 1, 5]])

In [36]:
eq5 = M[0,:]*3 - M[1,:]
eq5

matrix([[ 3,  1,  0, 12]])

In [37]:
eq6 = M[1,:]*3 - M[2,:]
eq6

matrix([[ 8,  2,  0, 38]])

In [38]:
eq7 = eq6-eq5*2
eq7

matrix([[ 2,  0,  0, 14]])

In [68]:
eq8 = eq7/2
eq8=eq8.astype(int)
eq8

matrix([[1, 0, 0, 7]])

In [69]:
eq9 = M[2,:]-eq8
eq9

matrix([[0, 4, 9, 9]])

In [73]:
eq10 = (eq9-eq4*9)/4
eq10=eq10.astype(int)
eq10

matrix([[ 0,  1,  0, -9]])

In [77]:
R = eq8
R = np.append(R,eq10,axis=0)
R = np.append(R,eq4,axis=0)
R

matrix([[ 1,  0,  0,  7],
        [ 0,  1,  0, -9],
        [ 0,  0,  1,  5]])

## Task 2 ##

In [9]:
A = np.matrix([
    [2,1,1],
    [3,2,3],
    [1,4,9]
])
A

matrix([[2, 1, 1],
        [3, 2, 3],
        [1, 4, 9]])

In [10]:
B = np.matrix([
    [10],
    [18],
    [16]
])
B

matrix([[10],
        [18],
        [16]])

In [11]:
INA =np.linalg.inv(A)
print(INA)

[[-3.   2.5 -0.5]
 [12.  -8.5  1.5]
 [-5.   3.5 -0.5]]


In [12]:
X = np.dot(INA,B)
print(X)

[[ 7.]
 [-9.]
 [ 5.]]


## Task 3 ##

In [13]:
A = np.matrix([
    [2,1,1],
    [3,2,3],
    [1,4,9]
])
A = A*1.0
print(A)

[[2. 1. 1.]
 [3. 2. 3.]
 [1. 4. 9.]]


In [14]:
B = np.matrix([
    [10],
    [18],
    [16]
])
B = B*1.0
print(B)

[[10.]
 [18.]
 [16.]]


In [15]:
def fwd_elim(AB):
    AB_re = AB.copy()
    [nr,nc] = AB_re.shape
    
    #set i as the Iteration index
    for i in range(1,nr):
        #print('Iteration #{}: '.format(i))
        #set r as the row index to work on
        for r in range(i,nr):
            #print('  working on row #{}'.format(r))
            #iteration index represent the order of the variable that we want to eliminate
            row_factor = AB_re[r,i-1]/AB_re[i-1,i-1]
            AB_re[r,:] = AB_re[r,:] - AB_re[i-1,:]*row_factor
        #end for r
    #end for i
    print(AB_re)
    return AB_re
#end function

In [16]:
AB = np.append(A,B,axis=1)
AB = AB *1.0
print(AB)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]]


In [17]:
AB_re = fwd_elim(AB)

[[  2.    1.    1.   10. ]
 [  0.    0.5   1.5   3. ]
 [  0.    0.   -2.  -10. ]]


In [18]:
print(AB_re)

[[  2.    1.    1.   10. ]
 [  0.    0.5   1.5   3. ]
 [  0.    0.   -2.  -10. ]]


In [19]:
def back_sub(AB_re):
    [nr,nc] = AB_re.shape
    #nr will represent the total number of variables that we have to find
    #create x to hold calculated values
    X = np.empty(nr)
    
    # v is the variable iterator (index)
    for v in range(nr-1,-1,-1):
        #print('v = {}'.format(v))
        #x = (constant - (sum_of_products between coeff_i and x_i))/coeff of x_v
        #where i>v
        
        sum_of_products = 0
        for i in range(v+1,nr):
            #print('  i = {}'.format(i))
            product = AB_re[v,i]*X[i]
            sum_of_products = sum_of_products + product
        #end for i
        X[v] = (AB_re[v,nc-1] - sum_of_products)/AB_re[v,v]
    #end for v
    print(X)
    return X
#end function

In [20]:
X = back_sub(AB_re)

[ 7. -9.  5.]


In [21]:
def fwd_elim_recurse(AB):
    [nr,nc] = AB.shape
    ABX = AB.copy()
    
    if(nr == 1):
        #don't do anything
        pass
    else:
        # r is the iterator for the rows whose first element removed
        for r in range(1,nr):
            row_factor = ABX[r,0]/ABX[0,0]
            ABX[r,:] = ABX[r,:] - ABX[0,:]*row_factor
        #end for
        print(ABX)
        #define the red box to be send to the next recursion
        red_box = ABX[1:nr,1:nc].copy()
        print(red_box)
        temp = fwd_elim_recurse(red_box)
        ABX[1:nr,1:nc] = temp
    #end if
    return ABX
#end function
    

In [22]:
print(AB)

[[ 2.  1.  1. 10.]
 [ 3.  2.  3. 18.]
 [ 1.  4.  9. 16.]]


In [23]:
fwd_elim_recurse(AB)

[[ 2.   1.   1.  10. ]
 [ 0.   0.5  1.5  3. ]
 [ 0.   3.5  8.5 11. ]]
[[ 0.5  1.5  3. ]
 [ 3.5  8.5 11. ]]
[[  0.5   1.5   3. ]
 [  0.   -2.  -10. ]]
[[ -2. -10.]]


matrix([[  2. ,   1. ,   1. ,  10. ],
        [  0. ,   0.5,   1.5,   3. ],
        [  0. ,   0. ,  -2. , -10. ]])

## Task 4 ##

In [24]:
def Cramer_Rule(X,Y,n):
    for i in range (0,n):
        A = X.copy()
        A[:,i] = Y
        print(A)
        ans = np.linalg.det(A)/np.linalg.det(X)
        print(round(ans))

In [25]:
A = np.matrix([
    [2,-5],
    [3,1]
])

B = np.matrix([
    [15],
    [31]
])

Cramer_Rule(A,B,len(A))

[[15 -5]
 [31  1]]
10.0
[[ 2 15]
 [ 3 31]]
1.0


In [26]:
A = np.matrix([
    [2,1,1],
    [3,2,3],
    [1,4,9]
])

B = np.matrix([
    [10],
    [18],
    [16]
])

Cramer_Rule(A,B,len(A))

[[10  1  1]
 [18  2  3]
 [16  4  9]]
7.0
[[ 2 10  1]
 [ 3 18  3]
 [ 1 16  9]]
-9.0
[[ 2  1 10]
 [ 3  2 18]
 [ 1  4 16]]
5.0


In [27]:
A = np.matrix([
    [1,2,1,4],
    [2,0,4,3],
    [4,2,2,1],
    [-3,1,3,2]
])

B = np.matrix([
    [13],
    [28],
    [20],
    [6]
])

Cramer_Rule(A,B,len(A))

[[13  2  1  4]
 [28  0  4  3]
 [20  2  2  1]
 [ 6  1  3  2]]
3.0
[[ 1 13  1  4]
 [ 2 28  4  3]
 [ 4 20  2  1]
 [-3  6  3  2]]
-1.0
[[ 1  2 13  4]
 [ 2  0 28  3]
 [ 4  2 20  1]
 [-3  1  6  2]]
4.0
[[ 1  2  1 13]
 [ 2  0  4 28]
 [ 4  2  2 20]
 [-3  1  3  6]]
2.0


## Task 5 ##

In [28]:
AB2 = np.array([
    [0,2,5,1],
    [2,1,1,1],
    [3,1,0,2]
])

AB2 = AB2 *1.0
print(AB2)

[[0. 2. 5. 1.]
 [2. 1. 1. 1.]
 [3. 1. 0. 2.]]


In [29]:
#(rearrange the rows)
temp = AB2[0,:].copy()
AB2[0,:] = AB2[2,:].copy()
AB2[2,:] = temp

In [30]:
def fwd_elim_recurse(AB):
    [nr,nc] = AB.shape
    ABX = AB.copy()
    # partialpivoting
    #(student work on this)
    #(rearrange the rows)
    
    if(nr == 1):
        #don't do anything
        pass
    else:
        # r is the iterator for the rows whose first element removed
        for r in range(1,nr):
            row_factor = ABX[r,0]/ABX[0,0]
            ABX[r,:] = ABX[r,:] - ABX[0,:]*row_factor
        #end for
        print(ABX)
        #define the red box to be send to the next recursion
        red_box = ABX[1:nr,1:nc].copy()
        print(red_box)
        temp = fwd_elim_recurse(red_box)
        ABX[1:nr,1:nc] = temp
    #end if
    return ABX
#end function
    

In [31]:
AB_re2 = fwd_elim_recurse(AB2)
print(AB_re2)

[[ 3.          1.          0.          2.        ]
 [ 0.          0.33333333  1.         -0.33333333]
 [ 0.          2.          5.          1.        ]]
[[ 0.33333333  1.         -0.33333333]
 [ 2.          5.          1.        ]]
[[ 0.33333333  1.         -0.33333333]
 [ 0.         -1.          3.        ]]
[[-1.  3.]]
[[ 3.          1.          0.          2.        ]
 [ 0.          0.33333333  1.         -0.33333333]
 [ 0.          0.         -1.          3.        ]]


In [32]:
X2 = back_sub(AB_re2)
print(X2)

[-2.  8. -3.]
[-2.  8. -3.]
